import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  // that is type we don't to cher char this one
  // here we accept the react.reactnode type accept kar rha hu

  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body bg-black
      className={inter.className }>

        <div className="relative w-full flex items-center justify-center">
        <Navbar/>
        
        </div>

        

        {children}
        </body>
    </html>
  );
}
